language: android
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)
    - GRADLE_VERSION=4.4
    - BUILD_API=android-27
    - BUILD_TOOLS=build-tools-27.0.3
  matrix:
    - EMULATOR_API=android-19 EMULATOR_ABI=armeabi-v7a
    - EMULATOR_API=android-21 EMULATOR_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    # The SDK version used to compile your project
    - $BUILD_API
    # The BuildTools version used by your project
    - $BUILD_TOOLS

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  # Setup the correct gradle version.
  - wget http://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
  - unzip gradle-${GRADLE_VERSION}-bin.zip
  - export GRADLE_HOME=$PWD/gradle-${GRADLE_VERSION}
  - export PATH=$GRADLE_HOME/bin:$PATH

before_script:
  # Update all the packages.
  - echo y | sdkmanager --update
  # Install the system image.
  - echo y | sdkmanager "system-images;${EMULATOR_API};google_apis;${EMULATOR_ABI}"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;${EMULATOR_API};google_apis;${EMULATOR_ABI}"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  # Wait for the emulator to boot.
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait 40 gradle build connectedCheck